#!/bin/bash

# Display listening sockets with the associated PID and program name
ss -tulnpe | awk '
NR>1 {
    split($0, arr, " ")
    if ($1 == "tcp" || $1 == "udp") {
        printf "%s\t%s\t%s\t%s\t%s\t%s\n", arr[1], arr[5], arr[6], arr[4], arr[7], arr[8]
    }
}'
