#!/bin/bash

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"
ss -lntup -4 -6 | awk 'NR>1 {print $1, $2, $3, $4, $5, $6, $7}'
