#!/bin/bash

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

# Using ss to show listening TCP/UDP sockets with PID and program names
ss -tulnpe | awk '
NR>1 {
    if ($1 == "tcp" || $1 == "udp" || $1 == "tcp6" || $1 == "udp6") {
        printf "%-8s %-7s %-7s %-23s %-23s %-12s %-10s\n", $1, $2, $3, $5, $6, $7, $8
    }
}'
